pipeline {

environment {
    imagename = "annetta/site_test"
    registryCredential = 'docker_annetta'
    dockerImage = ''
  }

    agent any

    stages {
        stage('Cloning Git') {
            steps {
                git branch: 'main', credentialsId: 'id_rsa_git', url: 'git@github.com:annetta1/proj1.git'
            }
        }
        
 stage('Building image') {
      steps{
        script {
          dockerImage = docker.build imagename
        }
      }
    }

stage('Deploy Image') {
      steps{
        script {
          docker.withRegistry( '', registryCredential ) {
            dockerImage.push("$BUILD_NUMBER")
             dockerImage.push('latest')

          }
        }
      }
    }

stage('Remove Unused docker image') {
      steps{
        sh "docker rmi $imagename:$BUILD_NUMBER"
         sh "docker rmi $imagename:latest"

      }
    }

    }
}
