pipeline {

environment {
    imagename = "annetta/site_test"
    registryCredential = 'docker_annetta'
    dockerImage = ''
    dockerRun = "docker run -p 8080:80 -d --name my-site annetta/site_test:latest"

  }

    agent any

    stages {
        stage('Cloning Git') {
            steps {
                git branch: 'main', credentialsId: 'id_rsa_git', url: 'git@github.com:annetta1/proj1.git'
            }
        }
        
 stage('Building image') {
      steps{
        script {
          dockerImage = docker.build imagename
        }
      }
    }

stage('Deploy Image') {
      steps{
        script {
          docker.withRegistry( '', registryCredential ) {
            dockerImage.push("$BUILD_NUMBER")
             dockerImage.push('latest')

          }
        }
      }
    }

stage('Remove Unused docker image') {
      steps{
        sh "docker rmi $imagename:$BUILD_NUMBER"
         sh "docker rmi $imagename:latest"

      }
    }

stage('Run Container on Dev Server'){
 steps{

     sshagent(['id_rsa_ubuntu1']) {
sh "ssh -o StrictHostKeyChecking=no ann@192.168.0.106 bash -c \"docker container rm -f my-site; ${env.dockerRun} \" "


     }
}
   }


    }
}
